language: bash
services: docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=1.2.0
  matrix:
    - RUBY_VER=2.3.6 TAG=2.3.6 ALPINE_VER=3.7

script:
  - cd "${RUBY_VER:0:3}/alpine${ALPINE_VER}"
  - travis_retry make

after_success:
  - bash "${TRAVIS_BUILD_DIR}/travis-release.sh"

# vim:set et ts=2 sw=2:
