language: python

sudo: required

services:
  - docker

env:
  matrix:
    - VERSION=2.3

script:
  - cd ./"${VERSION}"/alpine3.4
  - make

after_success: |
  if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ("${TRAVIS_BRANCH}" == "master"  || -n "${TRAVIS_TAG}") ]]; then
    docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    make release
  fi
